# -*- coding: utf-8 -*-
"""Sales Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-rZxoymeGtdSyBS4MXenoEO-acWXCJs
"""

# Impoting Pandas
import pandas as pd

"""*------------------Day 01 :-----------------*

**-------------Load CSV File----------------**
"""

#Load CSV file into Data frame
df=pd.read_csv('/content/sales_data.csv')

"""*----------------Day 02:------------------*

**-----------Explore Data-------------------**
"""

print("Shape of dataset:", df.shape)
print("\nColumns:", df.columns)
print("\nData Types:\n", df.dtypes)

"""*------------------Day 03:-----------------*

**-------------Cleaning Data----------------**
"""

# Check for Missing Values
print("\nMissing Values: \n", df.isnull().sum())

# Since no missing values found, no filling required
# Remove duplicate rows if any

df.drop_duplicates(inplace=True)

"""*---------------Day 04:----------------*

**------------Analying Data--------------**
"""

# 1. Total Revenue
total_revenue = df['Total_Sales'].sum()

# 2. Average Order Value
average_order_value = df['Total_Sales'].mean()

# 3. Best-Selling Product (by revenue)
product_sales = df.groupby('Product')['Total_Sales'].sum()
best_product = product_sales.idxmax()
best_product_sales = product_sales.max()

# 4. Sales by Region (extra metric)
region_sales = df.groupby('Region')['Total_Sales'].sum().sort_values(ascending=False)

"""*---------------Day 05:----------------*

**------------Creating Report--------------**
"""

print("\n" + "="*40)
print("        SALES ANALYSIS REPORT")
print("="*40)

# Total Revenue
print(f"\nTotal Revenue: ₹{total_revenue:,.2f}")
print(f"Average Order Value: ₹{average_order_value:,.2f}")

# Best Selling Product
print(f"\nBest-Selling Product: {best_product}")
print(f"Revenue from {best_product}: ₹{best_product_sales:,.2f}")

print("\nSales by Region:")
print(region_sales)

#Insihts of the report
print("\n" + "="*40)
print("INSIGHTS:")
print("="*40)

print(f"- The top-performing product is '{best_product}', generating the highest revenue.")
print(f"- The {region_sales.index[0]} region contributes the most to overall sales.")
print("- The business shows consistent order value across transactions.")