# -*- coding: utf-8 -*-
"""Data Visualization Mastery with Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZeVjwm9uDbNZNj8IQK-pXiaeUY2J3w8

**----------  Project 06: Data Visualization Mastery with Seaborn   ---------------**

Create an Interactive Sales Dashboard with multiple chart types showing sales trends, customer segmentation, and product performance

**Requirements:**
1. Use Seaborn for statistical plots
2. Create at least 5 different chart types
3. Build interactive elements with Plotly
4. Design cohesive color scheme
5. Create professional dashboard layout
"""

#    Install Libraries

!pip install plotly seaborn

#  Importing all Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

#  Load the Uploaded CSV File

df = pd.read_csv('/content/sales_data.csv')

df.head()

#  Check Dataset

print(df.shape)

print(df.columns)

df.info()

#  Data Cleaning

# Convert Date column into datetime
df['Date'] = pd.to_datetime(df['Date'])

# Remove duplicates
df = df.drop_duplicates()

# Check missing values
print(df.isnull().sum())

df.head()

#  Dashboard Theme

sns.set_style("darkgrid")

sns.set_palette("viridis")

plt.rcParams['figure.figsize'] = (12,6)

#  KPI Metrics

total_sales = df['Total_Sales'].sum()

total_quantity = df['Quantity'].sum()

average_sales = df['Total_Sales'].mean()

total_customers = df['Customer_ID'].nunique()

print("Total Sales:", total_sales)

print("Total Quantity Sold:", total_quantity)

print("Average Sales:", average_sales)

print("Total Customers:", total_customers)

#  Sales Trend Line Chart

sales_trend = df.groupby('Date')['Total_Sales'].sum().reset_index()

plt.figure(figsize=(8,4))

sns.lineplot(
    data=sales_trend,
    x='Date',
    y='Total_Sales',
    marker='o'
)

plt.title('Sales Trend Over Time', fontsize=18)

plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.show()

#  Product Performance Bar Chart

product_sales = df.groupby('Product')['Total_Sales'].sum().reset_index()

plt.figure(figsize=(6,4))

sns.barplot(
    data=product_sales,
    x='Product',
    y='Total_Sales'
)

plt.title('Product Performance', fontsize=18)
plt.xlabel('Product')
plt.ylabel('Total Sales')
plt.show()

#  Region-wise Sales

region_sales = df.groupby('Region')['Total_Sales'].sum().reset_index()

plt.figure(figsize=(5,4))

sns.barplot(
    data=region_sales,
    x='Region',
    y='Total_Sales'
)

plt.title('Region-wise Sales')
plt.show()

#  Sales Distribution Histogram

plt.figure(figsize=(7,4))

sns.histplot(
    df['Total_Sales'],
    bins=20,
    kde=True
)

plt.title('Sales Distribution')
plt.xlabel('Total Sales')
plt.show()

# Quantity vs Sales Scatter Plot

plt.figure(figsize=(7,4))

sns.scatterplot(
    data=df,
    x='Quantity',
    y='Total_Sales',
    hue='Product',
    s=120
)

plt.title('Quantity vs Total Sales')
plt.show()

#  Box Plot (Product Sales Distribution)

plt.figure(figsize=(7,4))

sns.boxplot(
    data=df,
    x='Product',
    y='Total_Sales'
)

plt.title('Sales Distribution by Product')
plt.show()

#  Correlation Heatmap

numeric_df = df[['Quantity', 'Price', 'Total_Sales']]

corr_matrix = numeric_df.corr()

plt.figure(figsize=(8,6))

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Heatmap')
plt.show()

#  Professional Multi-Chart Dashboard

fig, axes = plt.subplots(2, 2, figsize=(15,9))

# Product Sales
sns.barplot(
    data=product_sales,
    x='Product',
    y='Total_Sales',
    ax=axes[0,0]
)

axes[0,0].set_title("Product Performance")

# Region Sales
sns.barplot(
    data=region_sales,
    x='Region',
    y='Total_Sales',
    ax=axes[0,1]
)

axes[0,1].set_title("Region-wise Sales")

# Histogram
sns.histplot(
    df['Total_Sales'],
    kde=True,
    ax=axes[1,0]
)

axes[1,0].set_title("Sales Distribution")

# Scatter Plot
sns.scatterplot(
    data=df,
    x='Quantity',
    y='Total_Sales',
    hue='Product',
    ax=axes[1,1]
)

axes[1,1].set_title("Quantity vs Sales")

plt.tight_layout()
plt.show()

#  Interactive Plotly Line Chart

fig =px.line(
    sales_trend,
    x='Date',
    y='Total_Sales',
    title='Interactive Sales Trend',
    markers=True
)
fig.update_layout(
    width=900,
    height=500
)
fig.show()

#  Interactive Product Dashboard

fig = px.bar(
    product_sales,
    x='Product',
    y='Total_Sales',
    color='Product',
    title='Interactive Product Performance'
)
fig.update_layout(
    width=900,
    height=500
)
fig.show()

#   Interactive Scatter Plot

fig = px.scatter(
    df,
    x='Quantity',
    y='Total_Sales',
    color='Product',
    hover_data=['Region', 'Price'],
    size='Price',
    title='Interactive Quantity vs Sales'
)
fig.update_layout(
    width=900,
    height=500
)
fig.show()

#  FINAL INTERACTIVE SALES DASHBOARD

fig = make_subplots(
    rows=2,
    cols=2,
    subplot_titles=(
        'Sales Trend',
        'Product Performance',
        'Region Sales',
        'Quantity vs Sales'
    )
)

# Sales Trend
fig.add_trace(
    go.Scatter(
        x=sales_trend['Date'],
        y=sales_trend['Total_Sales'],
        mode='lines+markers',
        name='Sales Trend'
    ),
    row=1,
    col=1
)

# Product Performance
fig.add_trace(
    go.Bar(
        x=product_sales['Product'],
        y=product_sales['Total_Sales'],
        name='Products'
    ),
    row=1,
    col=2
)

# Region Sales
fig.add_trace(
    go.Bar(
        x=region_sales['Region'],
        y=region_sales['Total_Sales'],
        name='Regions'
    ),
    row=2,
    col=1
)

# Scatter Plot
fig.add_trace(
    go.Scatter(
        x=df['Quantity'],
        y=df['Total_Sales'],
        mode='markers',
        name='Sales Scatter'
    ),
    row=2,
    col=2
)

fig.update_layout(
    height=800,
    width=1400,
    title_text="Interactive Sales Dashboard",
    template="plotly_dark",
    showlegend=False
)

fig.show()

#  Save Dashboard

plt.savefig("sales_dashboard.png")