# -*- coding: utf-8 -*-
"""Project: Personal Introduction Program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYf-BOsFsGR7Bhes9-5o_rrif52S-DDA
"""

print("  Hellow world ! \n  My name Is MD AFROZ ANSARI \n \t Welcome to new world of coding in Data science ........")

# " AIM : Create a program that asks for user's name, age, and hobby, then displays a friendly welcome message with their information "

name = input("What is your Name? \t")

age = input("What is your age ? \t")

Hobby = input("What are your Hobbies ? \t ")

# The Welcome Message

print(f" Welcome {name} ! ")

print(f"You are {age} years old and love to {Hobby}")

