# -*- coding: utf-8 -*-
"""Ecommerce-Sales-Analysis Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCYXPITkYZSk4yYU4U9K7Ld4D8WPFIAS

Project Setup - Choose topic, collect data, create folder structure

Topic: **E-commerce Sales Analysis**
Data: /content/sales_data.csv
"""

# ------------------  1. Import & Load Data ---------------------

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('/content/sales_data.csv')

# Preview
df.head()

# ------------------ Error Handling --------------

try:
    df = pd.read_csv('/content/sales_data.csv')
    print("Data loaded successfully!")
except FileNotFoundError:
    print("Error: File not found. Check the file path.")
except Exception as e:
    print(f"Unexpected error: {e}")

# ------------------    2. Basic Validation ----------------------

# Check missing values
print(df.isnull().sum())

# Check data types
print(df.dtypes)

# Convert Date to datetime
df['Date'] = pd.to_datetime(df['Date'])

# ------------------------- 3. Data Cleaning -----------------

# Remove duplicates
df.drop_duplicates(inplace=True)

# Ensure Total_Sales is correct
df['Calculated_Sales'] = df['Quantity'] * df['Price']

# Validate
print((df['Total_Sales'] == df['Calculated_Sales']).all())

"""**-----------------------------------Analysis----------------------------------**"""

# 1. Total Revenue
total_revenue = df['Total_Sales'].sum()
print("Total Revenue:", total_revenue)
print("\n")

# 2. Sales by Product
product_sales = df.groupby('Product')['Total_Sales'].sum().sort_values(ascending=False)
print(product_sales)
print("\n")

# 3. Sales by Region
region_sales = df.groupby('Region')['Total_Sales'].sum()
print(region_sales)
print("\n")

# 4. Monthly Trend
df['Month'] = df['Date'].dt.to_period('M')
monthly_sales = df.groupby('Month')['Total_Sales'].sum()
print(monthly_sales)

"""**---------------Visualizations - Making charts with matplotlib----------------**"""

# 1. Chart 1: Sales by Product (Bar Chart)

plt.figure(figsize=(6,4))
product_sales.plot(kind='bar')
plt.title('Sales by Product')
plt.xlabel('Product')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('sales_by_product.png')
plt.show()

# Chart 2: Sales by Region (Pie Chart)

plt.figure(figsize=(6,4))
region_sales.plot(kind='pie', autopct='%1.1f%%')
plt.title('Sales Distribution by Region')
plt.ylabel('')
plt.savefig('sales_by_region.png')
plt.show()

# Chart 3: Monthly Trend (Line Chart)

plt.figure(figsize=(5,3))
monthly_sales.plot()
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.xticks(rotation=45)
plt.savefig('monthly_sales.png')
plt.show()

"""**Insight/Report**

**Key Insights**

1. **Top-Performing Product**
The analysis indicates that Phones are the top-performing product category, contributing the highest share of total revenue. This suggests strong customer demand and higher transaction value associated with this product segment compared to others.

2.**Regional Performance**

From a geographical perspective, the North and East regions demonstrate the strongest sales performance. These regions account for a significant portion of overall revenue, indicating better market penetration or higher purchasing activity in these areas.

3. **Sales Trend Over Time**

The monthly sales analysis shows a consistent trend with minor fluctuations across different periods. This indicates relatively stable business performance, without extreme spikes or drops, suggesting steady demand over time.

4. **Customer Purchase Behavior**

The data reveals that high-value sales are often driven by fewer transactions involving larger quantities. This pattern suggests that bulk purchasing plays an important role in overall revenue generation, highlighting the importance of targeting such customers.
"""