# -*- coding: utf-8 -*-
"""Statistical Business Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_UD3E_NoqCTHlMJ3Dy78tHCJdwXmtWg9

Project: Customer Sales Analysis

Analyze customer purchasing patterns, identify top customers, and create a comprehensive sales performance dashboard

Step 01: ------------------ Importing Libraries-----------------------
"""

# Data Handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Statistics
from scipy import stats
from scipy.stats import shapiro, ttest_1samp, ttest_ind, f_oneway

# Regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

"""Step 02: -----------------Loading of CSV files------------------------"""

sales_df = pd.read_csv("/content/sales_data.csv")
churn_df = pd.read_csv("/content/customer_churn.csv")

"""STEP 03: -------------------- Check Dataset Structure---------------------"""

print(" Show Sales Data \n")
print(sales_df.head())

print(sales_df.info())

print(sales_df.columns)

print("\n Show Customer Churn Data \n")
print(churn_df.head())

print(churn_df.info())

print(churn_df.columns)

"""STEP 04: ------------------- Descriptive Statistics--------------------

Calculate Mean, Median, Mode, Standard Deviation
"""

sales = sales_df["Total_Sales"]

print("Mean:", sales.mean())

print("Median:", sales.median())

print("Mode:", sales.mode()[0])

print("Standard Deviation:", sales.std())

print("Minimum:", sales.min())

print("Maximum:", sales.max())

"""STEP 05:------------------- Full Statistical Summary----------------------"""

print(sales.describe())

"""STEP 06:- --------------- Histogram (Distribution Analysis)---------------"""

plt.figure(figsize=(6,4))

sns.histplot(sales, kde=True)

plt.title("Sales Distribution")

plt.xlabel("Sales")

plt.ylabel("Frequency")

plt.show()

"""STEP 07: ----------------- Boxplot (Outlier Detection)--------------------------"""

plt.figure(figsize=(6,4))

sns.boxplot(x=sales)

plt.title("Sales Boxplot")

plt.show()

"""STEP 08: ------------------ Normal Distribution Test-----------------------

Using Shapiro-Wilk Test.

Hypothesis

H₀ → Data is normal

H₁ → Data is not normal
"""

stat, p = shapiro(sales)

print("Test Statistic:", stat)

print("P-value:", p)

if p > 0.05:
    print("Data is normally distributed")
else:
    print("Data is NOT normally distributed")

"""STEP 09: ---------------------- Correlation Analysis-----------------------"""

# First check numeric columns.

print(sales_df.select_dtypes(include=np.number).columns)

# If dataset has: Price, Quantity, Total_Sales

correlation = sales_df["Price"].corr(sales_df["Total_Sales"])

print("Correlation:", correlation)

"""STEP 10:---------------------- Correlation Heatmap---------------------"""

plt.figure(figsize=(8,4))

sns.heatmap(
    sales_df.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()

"""STEP 11: -------------------- Hypothesis Test 1 (One Sample T-Test) ----------------

**Business Question:**  Are average sales different from target sales?

Suppose target sales = 150000

Hypothesis:
H₀ → Average sales = 150000
H₁ → Average sales ≠ 150000
"""

stat, p = ttest_1samp(sales, 150000)

print("T-statistic:", stat)

print("P-value:", p)

if p < 0.05:
    print("Significant difference")
else:
    print("No significant difference")

"""STEP 12: -------------------- Hypothesis Test 2 (Independent T-Test)----------------

If dataset has regions: East and  West
"""

east_sales = sales_df[sales_df["Region"] == "East"]["Total_Sales"]

west_sales = sales_df[sales_df["Region"] == "West"]["Total_Sales"]

stat, p = ttest_ind(east_sales, west_sales)

print("P-value:", p)

if p < 0.05:
    print("Regions are significantly different")
else:
    print("No significant difference")

"""STEP 13: ------------------- Hypothesis Test 3 (ANOVA)----------------------

Testing multiple regions together.
"""

north = sales_df[sales_df["Region"] == "North"]["Total_Sales"]

south = sales_df[sales_df["Region"] == "South"]["Total_Sales"]

east = sales_df[sales_df["Region"] == "East"]["Total_Sales"]

west = sales_df[sales_df["Region"] == "West"]["Total_Sales"]

stat, p = f_oneway(north, south, east, west)

print("P-value:", p)

if p < 0.05:
    print("At least one region differs significantly")
else:
    print("No significant regional difference")

"""STEP 14: ----------------------- Confidence Interval-----------------------

95% Confidence Interval

"""

confidence_level = 0.95

mean = np.mean(sales)

sem = stats.sem(sales)

ci = stats.t.interval(
    confidence=confidence_level,
    df=len(sales)-1,
    loc=mean,
    scale=sem
)

print("95% Confidence Interval:")
print(ci)

"""STEP 15: ----------------- Linear Regression---------------------

Suppose:  X = Price and y = Total_Sales
"""

# Forula: y=mx+b

X = sales_df[["Price"]]
y = sales_df["Total_Sales"]

model = LinearRegression()

model.fit(X, y)

predictions = model.predict(X)

print("Coefficient:", model.coef_[0])
print("Intercept:", model.intercept_)
print("R-squared:", r2_score(y, predictions))

"""STEP 16: ------------------ Regression Plot--------------------"""

plt.figure(figsize=(8,4))

sns.regplot(
    x=sales_df["Price"],
    y=sales_df["Total_Sales"]
)

plt.title("Regression Analysis")
plt.show()

"""STEP 17: --------------------- Customer Churn Analysis------------------------"""

print(churn_df["Churn"].value_counts())

print(churn_df["Churn"].value_counts(normalize=True) * 100)

"""STEP 18: ------------------------- Churn vs Monthly Charges--------------------"""

sns.boxplot(
    x="Churn",
    y="MonthlyCharges",
    data=churn_df
)

plt.title("Monthly Charges vs Churn")
plt.show()

"""STEP 19: --------------------- Final Business Insights -----------------------"""

print("""
BUSINESS INSIGHTS

1. Sales are highly variable.
2. Price positively impacts total sales.
3. Regional sales differences exist.
4. Some churned customers have higher monthly charges.
5. Business should optimize pricing and customer retention strategies.
""")