# -*- coding: utf-8 -*-
"""Project 07: Statistical Business Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ghgEKBUjY21muqYUJbxTZq5gchu33f0n

***___________________________ Project 07: Statistical Business Analysis___________________________***

**Requirement :** Conduct hypothesis tests on sales data, analyze correlations between marketing spend

and revenue, provide statistical insights
"""

#  ---------------Importing Required Libraries------------------------

# Data handling
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Statistical analysis
from scipy import stats
from scipy.stats import ttest_ind, f_oneway

# Machine learning / regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Ignore warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

# ----------------------- Load the CSV Files ------------------------
# Load sales dataset
sales_df = pd.read_csv('sales_data.csv')

# Load customer churn dataset
churn_df = pd.read_csv('customer_churn.csv')

# Display first 5 rows
print(sales_df.head())
print(churn_df.head())

# ----------------------- Basic Dataset Information ---------------------------

# Check shape of datasets
print('Sales Dataset Shape:', sales_df.shape)
print('Churn Dataset Shape:', churn_df.shape)

# Check column names and data types
print(sales_df.info())
print(churn_df.info())

"""DESCRIPTIVE STATISTICS :

Mean = Average value

Median = Middle value

Mode = Most frequent value

Standard deviation = Spread of data

**--------------------- Descriptive Statistics ---------------------------**

Calculating mean, median, mode, standard deviation
"""

# ----------------DESCRIPTIVE STATISTICS --------------------

# Calculate Mean, Median, Mode, Standard Deviation

# Select numerical columns from sales dataset
sales_numeric = sales_df[['Quantity', 'Price', 'Total_Sales']]

# Calculate descriptive statistics
print('\nDESCRIPTIVE STATISTICS')
print(sales_numeric.describe())

# Mean
print('\nMean Values:')
print(sales_numeric.mean())

# Median
print('\nMedian Values:')
print(sales_numeric.median())

# Mode
print('\nMode Values:')
print(sales_numeric.mode().iloc[0])

# Standard Deviation
print('\nStandard Deviation:')
print(sales_numeric.std())

"""**--------------------- Data Distribution Analysis -----------------------**

Create histograms, test for normal distribution
"""

# ---------------------- DATA DISTRIBUTION ANALYSIS ------------------------

#-----------------Create Histograms

# Histogram for Total Sales
plt.figure(figsize=(6,4))
plt.hist(sales_df['Total_Sales'], bins=15)
plt.title('Distribution of Total Sales')
plt.xlabel('Total Sales')
plt.ylabel('Frequency')
plt.show()

#-----------------Test for Normal Distribution

# Shapiro-Wilk test checks normality
# H0 = Data is normally distributed
# H1 = Data is NOT normally distributed

shapiro_test = stats.shapiro(sales_df['Total_Sales'])

print('\nSHAPIRO-WILK TEST')
print('Test Statistic:', shapiro_test.statistic)
print('P-value:', shapiro_test.pvalue)

# Decision rule
if shapiro_test.pvalue > 0.05:
    print('Data appears normally distributed')
else:
    print('Data is NOT normally distributed')

"""**--------------------Correlation Analysis --------------------**

Calculate Pearson correlation, create heatmap
"""

# ---------------------- CORRELATION ANALYSIS -----------------------------

#-----------------------Pearson Correlation

# Correlation matrix for numerical columns
correlation_matrix = sales_numeric.corr(method='pearson')


print('\nCORRELATION MATRIX')
print(correlation_matrix)


#-----------------------Heatmap Visualization

# Create heatmap for correlations
plt.figure(figsize=(6,4))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()


#----------------------Correlation Interpretation

# Correlation between Quantity and Total Sales
corr_value = sales_df['Quantity'].corr(sales_df['Total_Sales'])

print(f'Correlation between Quantity and Total Sales: {corr_value:.2f}')


# Interpretation
if corr_value > 0.7:
    print('Strong positive correlation')
elif corr_value > 0.3:
    print('Moderate positive correlation')
else:
    print('Weak correlation')

"""**----------------------HYPOTHESIS TESTING ---------------------------**

(In this We will perform 3 hypothesis tests.)

**Hypothesis Test 1: Independent T-Test**

Question: Is there a significant difference in Total Sales between East and West regions?

**Hypothesis Test 2: ANOVA Test**

Question: Do different products generate significantly different sales?

**Hypothesis Test 3: One-Sample T-Test**

Question: Is the average monthly charge greater than 100?
"""

#-------------------Hypothesis Test 1: Independent T-Test

# Question: Is there a significant difference in Total Sales between East and West regions?

# Extracting sales data for East and West regions.
east_sales = sales_df[sales_df['Region'] == 'East']['Total_Sales']
west_sales = sales_df[sales_df['Region'] == 'West']['Total_Sales']

# Perform independent t-test
# H0 = No difference between means
# H1 = Significant difference exists

ttest_result = ttest_ind(east_sales, west_sales)

print('\nT-TEST RESULT')
print('T-statistic:', ttest_result.statistic)
print('P-value:', ttest_result.pvalue)


# Interpretation
if ttest_result.pvalue < 0.05:
    print('Reject H0 -> Significant difference exists')
else:
    print('Fail to reject H0 -> No significant difference')


#------------------- Hypothesis Test 2: ANOVA Test

# Question: Do different products generate significantly different sales?

# Group total sales by product
laptop_sales = sales_df[sales_df['Product'] == 'Laptop']['Total_Sales']
phone_sales = sales_df[sales_df['Product'] == 'Phone']['Total_Sales']
headphone_sales = sales_df[sales_df['Product'] == 'Headphones']['Total_Sales']


# Performing ANOVA
# H0 = All group means are equal
# H1 = At least one group mean is different

anova_result = f_oneway(laptop_sales, phone_sales, headphone_sales)

print('\nANOVA TEST RESULT')
print('F-statistic:', anova_result.statistic)
print('P-value:', anova_result.pvalue)

# Interpretation
if anova_result.pvalue < 0.05:
    print('Reject H0 -> Product sales differ significantly')
else:
    print('Fail to reject H0 -> No significant difference')


#------------------- Hypothesis Test 3: One-Sample T-Test

# Question: Is the average monthly charge greater than 100?

# Perform one-sample t-test
# H0 = Mean monthly charge = 100
# H1 = Mean monthly charge > 100

monthly_test = stats.ttest_1samp(churn_df['MonthlyCharges'], 100)

print('\nONE-SAMPLE T-TEST')
print('T-statistic:', monthly_test.statistic)
print('P-value:', monthly_test.pvalue)


# Interpretation
if monthly_test.pvalue < 0.05:
    print('Reject H0 -> Average monthly charge is significantly different')
else:
    print('Fail to reject H0 -> No significant difference')

"""**-------------------------CONFIDENCE INTERVALS ---------------------------**

Calculate 95% Confidence Interval for Average Sales and determine margin of errors
"""

#--------------------- Calculate sample mean
mean_sales = sales_df['Total_Sales'].mean()

#---------------------- Standard error
std_error = stats.sem(sales_df['Total_Sales'])

#---------------------- 95% confidence interval
confidence_interval = stats.t.interval(
    confidence=0.95,
    df=len(sales_df['Total_Sales']) - 1,
    loc=mean_sales,
    scale=std_error)

print('\n95% CONFIDENCE INTERVAL')
print('Average Sales:', round(mean_sales, 2))
print('Confidence Interval:', confidence_interval)

# --------------------- Margin of Error

# Margin of error calculation
margin_error = confidence_interval[1] - mean_sales

print('Margin of Error:', round(margin_error, 2))

"""**--------------------- Regression Analysis ----------------------**

 Performing linear regression and calculate R-squared

 R-squared tells how much variation is explained by the model.
Closer to 1 = better model.

"""

# ----------------------Linear Regression

# We will predict Total Sales using Quantity.

# Independent variable (must be 2D)
X = sales_df[['Quantity']]

# Dependent variable
y = sales_df['Total_Sales']

# Create regression model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Make predictions
predictions = model.predict(X)

# R-squared score
r2 = r2_score(y, predictions)


print('\nLINEAR REGRESSION RESULTS')
print('Intercept:', model.intercept_)
print('Coefficient:', model.coef_[0])
print('R-squared:', r2)


# --------------------Regression Visualization

# Scatter plot with regression line

plt.figure(figsize=(6,4))
plt.scatter(X, y)
plt.plot(X, predictions)
plt.title('Regression Analysis: Quantity vs Total Sales')
plt.xlabel('Quantity')
plt.ylabel('Total Sales')
plt.show()

"""**------------------------ Business Insights ------------------------**

Translate findings, creating actionable recommendations
"""

# ----------------Insights

print('\nSTATISTICAL ANALYSIS REPORT')
print('--------------------------------')

# Average sales insight
print(f'Average Sales: {mean_sales:.2f}')

# Correlation insight
print(f'Correlation (Quantity vs Total Sales): {corr_value:.2f}')

# Regression insight
print(f'Regression R-squared: {r2:.2f}')

# T-test insight
if ttest_result.pvalue < 0.05:
    print('Regional sales differences are statistically significant.')
else:
    print('Regional sales differences are not statistically significant.')

# ANOVA insight
if anova_result.pvalue < 0.05:
    print('Different products perform differently in terms of sales.')
else:
    print('Product sales performance is statistically similar.')

"""**-------------------------------   Final Business Recommendations ---------------------------------**

1. ***Focus on High Performing Products:*** If ANOVA shows significant differences, invest more marketing budget in top-performing products.

2. ***Improve Sales Strategy by Region:*** If regional differences are significant, optimize inventory and promotions region-wise.

3. ***Use Quantity Forecasting:*** Regression analysis shows how sales increase with quantity. This can help in demand forecasting.

4. ***Monitor Customer Charges:*** If customer monthly charges are significantly high, review pricing strategies to reduce churn risk.
"""